#!/usr/bin/python3
# Generated by Gemini from a couple of converted examples. Nifty!

import argparse
import os

def convert_pbm_to_bin(pbm_file, bin_file):
    print(f"Reading {pbm_file}...")
    
    try:
        with open(pbm_file, 'r') as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading {pbm_file}: {e}")
        return

    # Parse PBM data
    pixels = []
    width = None
    height = None
    
    for line in lines:
        line = line.strip()
        # Skip empty lines, comments, and the P1 magic number
        if not line or line.startswith('#') or line == 'P1':
            continue
            
        # Parse dimensions
        if width is None:
            parts = line.split()
            width = int(parts[0])
            height = int(parts[1])
            continue
        
        # Gather pixel data
        for char in line:
            if char in '01':
                pixels.append(int(char))
                
    if width != 640 or height != 200:
        print(f"Warning: Image is {width}x{height}, expected 640x200.")
        
    # Pack pixels into bytes (8 pixels per byte, MSB to LSB)
    packed_bytes = bytearray()
    for i in range(0, len(pixels), 8):
        byte_val = 0
        for bit in range(8):
            if i + bit < len(pixels):
                # PBM '0' is background, '1' is foreground.
                byte_val = (byte_val << 1) | pixels[i + bit]
            else:
                # Pad remaining bits with 0 if image is short
                byte_val = byte_val << 1
        packed_bytes.append(byte_val)
        
    # Construct the binary file data
    out_data = bytearray()
    
    # 1. BSAVE Header (7 bytes)
    out_data.append(0xFD)           # BSAVE Magic byte
    out_data.extend([0x42, 0x12])   # Segment: 0x1242
    out_data.extend([0x60, 0x00])   # Offset: 0x0060
    out_data.extend([0x84, 0x3E])   # Length: 16004 bytes (0x3E84)
    
    # 2. GET Array Header (4 bytes)
    out_data.extend([0x80, 0x02])   # Width: 640 (0x0280)
    out_data.extend([0xC8, 0x00])   # Height: 200 (0x00C8)
    
    # 3. Pixel data
    # Include all 16000 bytes for the full image
    out_data.extend(packed_bytes[:16000])
    target_length = 16011
    
    # Pad to exact length if the image was unexpectedly short
    while len(out_data) < target_length:
        out_data.append(0x00)
        
    # Write to destination binary file
    try:
        with open(bin_file, 'wb') as f:
            f.write(out_data)
        print(f"Successfully created {bin_file} (Size: {len(out_data)} bytes)")
    except Exception as e:
        print(f"Error writing {bin_file}: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert ASCII PBM to QuickBASIC BSAVE format.")
    parser.add_argument("input", help="Input .pbm file")
    parser.add_argument("output", help="Output .BIN file")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.input):
        print(f"File not found: {args.input}")
        exit(1)
        
    convert_pbm_to_bin(args.input, args.output)
